### ISSUE TITLE
URF_UNREAD_FIELD Error causes the build to fail

### ISSUE THREAD

**Issue by lakshya8066** [jenkinsci/in-toto-plugin#31]
### What feature do you want to see added?

There are a few fields that are declared and initialized but never read like [`transport`](https://github.com/jenkinsci/in-toto-plugin/blob/0f9eb92570c5c2e436dff4e6f11b35f76375f3eb/src/main/java/io/jenkins/plugins/intotorecorder/InTotoRecorder.java#L143) and [`keyPath`](https://github.com/jenkinsci/in-toto-plugin/blob/0f9eb92570c5c2e436dff4e6f11b35f76375f3eb/src/main/java/io/jenkins/plugins/intotorecorder/InTotoWrapper.java#L321). The fields should not be left unread according to the findbugs linter. This causes the build to fail. 

We should find a way to handle these fields or consider refactoring the fields depending on their usage.

### Upstream changes

The errors below refer to the code in this [PR](https://github.com/jenkinsci/in-toto-plugin/pull/29/files)

![image](https://user-images.githubusercontent.com/73181332/176439622-ba547329-b5af-4591-80bf-523d97f8e861.png)

**Comment by adityasaky** [comment]
Moved to https://github.com/in-toto/in-toto-jenkins-plugin/issues/2
